---
- name: run services
  hosts: services
  become: yes
  vars:
    ansible_ssh_user: mftiedu
    ansible_ssh_pass: cHONtic
    ansible_sudo_pass: cHONtic
    currency_service_image: artemon4uk/currencyservice
    weather_service_image: artemon4uk/weatherservice
    predict_service_image: artemon4uk/predictservice
    eureka_image: artemon4uk/eurekaservice
    path: /edu/alexandrov
    db_server: 194.87.111.112

  tasks:
    - name: pull currency
      command: docker pull "{{ currency_service_image }}"

    - name: pull weather
      command: docker pull "{{ weather_service_image }}"

    - name: pull predict
      command: docker pull "{{ predict_service_image }}"

    - name: pull eureka
      command: docker pull "{{ eureka_image }}"

    - name: create docker compose
      template:
        src: "{{ path }}/weather-currency-app/ansible/templates/docker-compose.yml.j2"
        dest: "{{ path }}/docker-compose.yml"

    - name: start
      docker_compose:
        project_src: "{{ path }}"