---
- name: run services
  hosts: local
  become: yes
  vars:
    ansible_ssh_user: mftiedu
    ansible_ssh_pass: cHONtic
    ansible_sudo_pass: cHONtic
    currency_service_image: artemon4uk/currencyservice
    weather_service_image: artemon4uk/weatherservice
    predict_service_image: artemon4uk/predictservice
    eureka_image: artemon4uk/eurekaserver
    path: /edu/alexandrov
    db_server: 194.87.111.112
    ansible_connection: local

  tasks:
    - name: create docker compose
      template:
        src: "{{ path }}/alexandrovHW/ansible/templates/docker-compose.yml.j2"
        dest: "{{ path }}/docker-compose.yml"

    - name: start
      docker_compose:
        project_src: "{{ path }}"