apiVersion: apps/v1
kind: Deployment
metadata:
  name: CurrencyService
spec:
  replicas: 2
  selector:
    matchLabels:
      app: CurrencyService
  template:
    metadata:
      name: CurrencyService
      labels:
        app: CurrencyService
    spec:
      containers:
        - image: artemon4uk/currencyservice
          name: currencyservice
          ports:
            - containerPort: 9002
          imagePullPolicy: IfNotPresent